### ISSUE TITLE
Testing against detrended light curves

### ISSUE THREAD

**Issue by RuthAngus** [RuthAngus/K2rotation#1]
![result](https://cloud.githubusercontent.com/assets/2834161/6274425/8f330658-b845-11e4-81cc-3706a2f7e3af.png)

The top panel shows Andrew's detrended lc. Middle shows Lomb Scargle (blue) and fft (green) of detrended lc. The bottom shows our periodogram of the non-detrended lc.

**Comment by dfm** [comment]
what's the epicid?

**Comment by RuthAngus** [comment]
201859398

**Comment by dfm** [comment]
If we switch to S/N like we tried earlier then this is what I get for that guy:

![pgram](https://cloud.githubusercontent.com/assets/350282/6274944/3b590038-b849-11e4-8fac-e9a50a4d2049.png)

Green is LS on Andrew's LC and blue is this new method.

**Comment by RuthAngus** [comment]
Here's 201748188 with 150 components...
![result](https://cloud.githubusercontent.com/assets/2834161/6274970/747647cc-b849-11e4-945a-efecfb620a1f.png)

**Comment by RuthAngus** [comment]
And 10 components:
![result](https://cloud.githubusercontent.com/assets/2834161/6274976/85fc7796-b849-11e4-8aa1-1436eb223eed.png)
